/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/uri.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>

#include "ExecutionApi.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

namespace {
[[maybe_unused]]
std::string selectPreferredContentType(const std::vector<std::string>& contentTypes) {
    if (contentTypes.size() == 0) {
        return "application/json";
    }

    if (contentTypes.size() == 1) {
        return contentTypes.at(0);
    }

    static const std::array<std::string, 2> preferredTypes = {"json", "xml"};
    for (const auto& preferredType: preferredTypes) {
        const auto ret = std::find_if(contentTypes.cbegin(),
        contentTypes.cend(),
        [preferredType](const std::string& str) {
            return str.find(preferredType) != std::string::npos;});
        if (ret != contentTypes.cend()) {
            return *ret;
        }
    }

    return contentTypes.at(0);
}
}

ExecutionApiException::ExecutionApiException(int status_code, std::string what)
  : m_status(status_code),
    m_what(what)
{

}
int ExecutionApiException::getStatus() const
{
    return m_status;
}
const char* ExecutionApiException::what() const noexcept
{
    return m_what.c_str();
}


template<class MODEL_T>
MODEL_T extractJsonModelBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto model = MODEL_T(pt);
    return model;
}

template<class MODEL_T>
std::vector<MODEL_T> extractJsonArrayBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto arrayRet = std::vector<MODEL_T>();
    for (const auto& child: pt) {
        arrayRet.emplace_back(MODEL_T(child.second));
    }
    return arrayRet;
}

template <class KEY_T, class VAL_T>
std::string convertMapResponse(const std::map<KEY_T, VAL_T>& map)
{
    boost::property_tree::ptree pt;
    for(const auto &kv: map) {
    pt.push_back(boost::property_tree::ptree::value_type(
        boost::lexical_cast<std::string>(kv.first),
        boost::property_tree::ptree(
        boost::lexical_cast<std::string>(kv.second))));
    }
    std::stringstream sstream;
    write_json(sstream, pt);
    std::string result = sstream.str();
    return result;
}

namespace ExecutionApiResources {
QueriesResource::QueriesResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/queries");
	this->set_method_handler("GET",
		std::bind(&QueriesResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> QueriesResource::handleExecutionApiException(const ExecutionApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> QueriesResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> QueriesResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void QueriesResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void QueriesResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void QueriesResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void QueriesResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    
    int status_code = 500;
    std::vector<ShallowQuery> resultObject = std::vector<ShallowQuery>();
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET();
    }
    catch(const ExecutionApiException& e) {
        std::tie(status_code, result) = handleExecutionApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, std::vector<ShallowQuery>> QueriesResource::handler_GET(
        )
{
    return handler_GET_func();
}


std::string QueriesResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string QueriesResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
QueryQueryIdResource::QueryQueryIdResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/query/{queryId: .*}");
	this->set_method_handler("GET",
		std::bind(&QueryQueryIdResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> QueryQueryIdResource::handleExecutionApiException(const ExecutionApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> QueryQueryIdResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> QueryQueryIdResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void QueryQueryIdResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void QueryQueryIdResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void QueryQueryIdResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void QueryQueryIdResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // Getting the path params
    std::string queryId = request->get_path_parameter("queryId", "");
    
    int status_code = 500;
    Query resultObject = Query{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(queryId);
    }
    catch(const ExecutionApiException& e) {
        std::tie(status_code, result) = handleExecutionApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, Query> QueryQueryIdResource::handler_GET(
        std::string & queryId)
{
    return handler_GET_func(queryId);
}


std::string QueryQueryIdResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string QueryQueryIdResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
ErrorQueryIdResource::ErrorQueryIdResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/error/{queryId: .*}");
	this->set_method_handler("GET",
		std::bind(&ErrorQueryIdResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> ErrorQueryIdResource::handleExecutionApiException(const ExecutionApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> ErrorQueryIdResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> ErrorQueryIdResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void ErrorQueryIdResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void ErrorQueryIdResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void ErrorQueryIdResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void ErrorQueryIdResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // Getting the path params
    std::string queryId = request->get_path_parameter("queryId", "");
    
    int status_code = 500;
    MultipleProblemsError resultObject = MultipleProblemsError{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(queryId);
    }
    catch(const ExecutionApiException& e) {
        std::tie(status_code, result) = handleExecutionApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, MultipleProblemsError> ErrorQueryIdResource::handler_GET(
        std::string & queryId)
{
    return handler_GET_func(queryId);
}


std::string ErrorQueryIdResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string ErrorQueryIdResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
ResultQueryIdResource::ResultQueryIdResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/result/{queryId: .*}");
	this->set_method_handler("GET",
		std::bind(&ResultQueryIdResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> ResultQueryIdResource::handleExecutionApiException(const ExecutionApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> ResultQueryIdResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> ResultQueryIdResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void ResultQueryIdResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void ResultQueryIdResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void ResultQueryIdResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void ResultQueryIdResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto getQueryResultRequest = extractJsonModelBodyParam<GetQueryResult_request>(bodyContent);
    // Getting the path params
    std::string queryId = request->get_path_parameter("queryId", "");
    
    int status_code = 500;
    std::vector<QueryResult_inner> resultObject = std::vector<QueryResult_inner>();
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(queryId, getQueryResultRequest);
    }
    catch(const ExecutionApiException& e) {
        std::tie(status_code, result) = handleExecutionApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
        "application/json, "
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, std::vector<QueryResult_inner>> ResultQueryIdResource::handler_GET(
        std::string & queryId, GetQueryResult_request & getQueryResultRequest)
{
    return handler_GET_func(queryId, getQueryResultRequest);
}


std::string ResultQueryIdResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string ResultQueryIdResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
QueryResource::QueryResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/query");
	this->set_method_handler("POST",
		std::bind(&QueryResource::handler_POST_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> QueryResource::handleExecutionApiException(const ExecutionApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> QueryResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> QueryResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void QueryResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void QueryResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void QueryResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void QueryResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto executeQueryRequest = extractJsonModelBodyParam<ExecuteQueryRequest>(bodyContent);
    
    int status_code = 500;
    std::string resultObject = "";
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_POST(executeQueryRequest);
    }
    catch(const ExecutionApiException& e) {
        std::tie(status_code, result) = handleExecutionApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
        "application/json, "
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject;
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Response used when more problems can occur in the system when processing request";
    
        result = resultObject.toJsonString();
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, std::string> QueryResource::handler_POST(
        ExecuteQueryRequest & executeQueryRequest)
{
    return handler_POST_func(executeQueryRequest);
}


std::string QueryResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string QueryResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}

} /* namespace ExecutionApiResources */

ExecutionApi::ExecutionApi(std::shared_ptr<restbed::Service> const& restbedService)
: m_service(restbedService)
{
}

ExecutionApi::~ExecutionApi() {}

std::shared_ptr<ExecutionApiResources::QueriesResource> ExecutionApi::getQueriesResource() {
    if (!m_spQueriesResource) {
        setResource(std::make_shared<ExecutionApiResources::QueriesResource>());
    }
    return m_spQueriesResource;
}
std::shared_ptr<ExecutionApiResources::QueryQueryIdResource> ExecutionApi::getQueryQueryIdResource() {
    if (!m_spQueryQueryIdResource) {
        setResource(std::make_shared<ExecutionApiResources::QueryQueryIdResource>());
    }
    return m_spQueryQueryIdResource;
}
std::shared_ptr<ExecutionApiResources::ErrorQueryIdResource> ExecutionApi::getErrorQueryIdResource() {
    if (!m_spErrorQueryIdResource) {
        setResource(std::make_shared<ExecutionApiResources::ErrorQueryIdResource>());
    }
    return m_spErrorQueryIdResource;
}
std::shared_ptr<ExecutionApiResources::ResultQueryIdResource> ExecutionApi::getResultQueryIdResource() {
    if (!m_spResultQueryIdResource) {
        setResource(std::make_shared<ExecutionApiResources::ResultQueryIdResource>());
    }
    return m_spResultQueryIdResource;
}
std::shared_ptr<ExecutionApiResources::QueryResource> ExecutionApi::getQueryResource() {
    if (!m_spQueryResource) {
        setResource(std::make_shared<ExecutionApiResources::QueryResource>());
    }
    return m_spQueryResource;
}
void ExecutionApi::setResource(std::shared_ptr<ExecutionApiResources::QueriesResource> resource) {
    m_spQueriesResource = resource;
    m_service->publish(m_spQueriesResource);
}
void ExecutionApi::setResource(std::shared_ptr<ExecutionApiResources::QueryQueryIdResource> resource) {
    m_spQueryQueryIdResource = resource;
    m_service->publish(m_spQueryQueryIdResource);
}
void ExecutionApi::setResource(std::shared_ptr<ExecutionApiResources::ErrorQueryIdResource> resource) {
    m_spErrorQueryIdResource = resource;
    m_service->publish(m_spErrorQueryIdResource);
}
void ExecutionApi::setResource(std::shared_ptr<ExecutionApiResources::ResultQueryIdResource> resource) {
    m_spResultQueryIdResource = resource;
    m_service->publish(m_spResultQueryIdResource);
}
void ExecutionApi::setResource(std::shared_ptr<ExecutionApiResources::QueryResource> resource) {
    m_spQueryResource = resource;
    m_service->publish(m_spQueryResource);
}
void ExecutionApi::setExecutionApiQueriesResource(std::shared_ptr<ExecutionApiResources::QueriesResource> spQueriesResource) {
    m_spQueriesResource = spQueriesResource;
    m_service->publish(m_spQueriesResource);
}
void ExecutionApi::setExecutionApiQueryQueryIdResource(std::shared_ptr<ExecutionApiResources::QueryQueryIdResource> spQueryQueryIdResource) {
    m_spQueryQueryIdResource = spQueryQueryIdResource;
    m_service->publish(m_spQueryQueryIdResource);
}
void ExecutionApi::setExecutionApiErrorQueryIdResource(std::shared_ptr<ExecutionApiResources::ErrorQueryIdResource> spErrorQueryIdResource) {
    m_spErrorQueryIdResource = spErrorQueryIdResource;
    m_service->publish(m_spErrorQueryIdResource);
}
void ExecutionApi::setExecutionApiResultQueryIdResource(std::shared_ptr<ExecutionApiResources::ResultQueryIdResource> spResultQueryIdResource) {
    m_spResultQueryIdResource = spResultQueryIdResource;
    m_service->publish(m_spResultQueryIdResource);
}
void ExecutionApi::setExecutionApiQueryResource(std::shared_ptr<ExecutionApiResources::QueryResource> spQueryResource) {
    m_spQueryResource = spQueryResource;
    m_service->publish(m_spQueryResource);
}


void ExecutionApi::publishDefaultResources() {
    if (!m_spQueriesResource) {
        setResource(std::make_shared<ExecutionApiResources::QueriesResource>());
    }
    if (!m_spQueryQueryIdResource) {
        setResource(std::make_shared<ExecutionApiResources::QueryQueryIdResource>());
    }
    if (!m_spErrorQueryIdResource) {
        setResource(std::make_shared<ExecutionApiResources::ErrorQueryIdResource>());
    }
    if (!m_spResultQueryIdResource) {
        setResource(std::make_shared<ExecutionApiResources::ResultQueryIdResource>());
    }
    if (!m_spQueryResource) {
        setResource(std::make_shared<ExecutionApiResources::QueryResource>());
    }
}

std::shared_ptr<restbed::Service> ExecutionApi::service() {
    return m_service;
}


}
}
}
}

