/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ExecutionApi.h
 *
 * 
 */

#ifndef ExecutionApi_H_
#define ExecutionApi_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "Error.h"
#include "ExecuteQueryRequest.h"
#include "GetQueryResult_request.h"
#include "MultipleProblemsError.h"
#include "Query.h"
#include "QueryResult_inner.h"
#include "ShallowQuery.h"
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  ExecutionApiException: public std::exception
{
public:
    ExecutionApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace ExecutionApiResources {
/// <summary>
/// Get list of queries (optional in project 3, but useful). Use those IDs to get details by calling /query endpoint.
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  QueriesResource: public restbed::Resource
{
public:
    QueriesResource(const std::string& context = "");
    virtual ~QueriesResource() = default;

    QueriesResource(
        const QueriesResource& other) = default; // copy constructor
    QueriesResource(QueriesResource&& other) noexcept = default; // move constructor

    QueriesResource& operator=(const QueriesResource& other) = default; // copy assignment
    QueriesResource& operator=(QueriesResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::vector<ShallowQuery>>(
        )> handler_GET_func =
            []() -> std::pair<int, std::vector<ShallowQuery>>
                { throw ExecutionApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::vector<ShallowQuery>> handler_GET(
        );


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleExecutionApiException(const ExecutionApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get detailed status of selected query
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  QueryQueryIdResource: public restbed::Resource
{
public:
    QueryQueryIdResource(const std::string& context = "");
    virtual ~QueryQueryIdResource() = default;

    QueryQueryIdResource(
        const QueryQueryIdResource& other) = default; // copy constructor
    QueryQueryIdResource(QueryQueryIdResource&& other) noexcept = default; // move constructor

    QueryQueryIdResource& operator=(const QueryQueryIdResource& other) = default; // copy assignment
    QueryQueryIdResource& operator=(QueryQueryIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, Query>(
        std::string & queryId)> handler_GET_func =
            [](std::string &) -> std::pair<int, Query>
                { throw ExecutionApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, Query> handler_GET(
        std::string & queryId);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleExecutionApiException(const ExecutionApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get error of selected query (will be available only for queries in FAILED state)
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  ErrorQueryIdResource: public restbed::Resource
{
public:
    ErrorQueryIdResource(const std::string& context = "");
    virtual ~ErrorQueryIdResource() = default;

    ErrorQueryIdResource(
        const ErrorQueryIdResource& other) = default; // copy constructor
    ErrorQueryIdResource(ErrorQueryIdResource&& other) noexcept = default; // move constructor

    ErrorQueryIdResource& operator=(const ErrorQueryIdResource& other) = default; // copy assignment
    ErrorQueryIdResource& operator=(ErrorQueryIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, MultipleProblemsError>(
        std::string & queryId)> handler_GET_func =
            [](std::string &) -> std::pair<int, MultipleProblemsError>
                { throw ExecutionApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, MultipleProblemsError> handler_GET(
        std::string & queryId);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleExecutionApiException(const ExecutionApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get result of selected query (will be available only for SELECT queries after they are completed)
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  ResultQueryIdResource: public restbed::Resource
{
public:
    ResultQueryIdResource(const std::string& context = "");
    virtual ~ResultQueryIdResource() = default;

    ResultQueryIdResource(
        const ResultQueryIdResource& other) = default; // copy constructor
    ResultQueryIdResource(ResultQueryIdResource&& other) noexcept = default; // move constructor

    ResultQueryIdResource& operator=(const ResultQueryIdResource& other) = default; // copy assignment
    ResultQueryIdResource& operator=(ResultQueryIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::vector<QueryResult_inner>>(
        std::string & queryId, GetQueryResult_request & getQueryResultRequest)> handler_GET_func =
            [](std::string &, GetQueryResult_request &) -> std::pair<int, std::vector<QueryResult_inner>>
                { throw ExecutionApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::vector<QueryResult_inner>> handler_GET(
        std::string & queryId, GetQueryResult_request & getQueryResultRequest);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleExecutionApiException(const ExecutionApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Submit new query for execution
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  QueryResource: public restbed::Resource
{
public:
    QueryResource(const std::string& context = "");
    virtual ~QueryResource() = default;

    QueryResource(
        const QueryResource& other) = default; // copy constructor
    QueryResource(QueryResource&& other) noexcept = default; // move constructor

    QueryResource& operator=(const QueryResource& other) = default; // copy assignment
    QueryResource& operator=(QueryResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::string>(
        ExecuteQueryRequest & executeQueryRequest)> handler_POST_func =
            [](ExecuteQueryRequest &) -> std::pair<int, std::string>
                { throw ExecutionApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::string> handler_POST(
        ExecuteQueryRequest & executeQueryRequest);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleExecutionApiException(const ExecutionApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_POST_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace ExecutionApiResources */

using ExecutionApiQueriesResource [[deprecated]] = ExecutionApiResources::QueriesResource;
using ExecutionApiQueryQueryIdResource [[deprecated]] = ExecutionApiResources::QueryQueryIdResource;
using ExecutionApiErrorQueryIdResource [[deprecated]] = ExecutionApiResources::ErrorQueryIdResource;
using ExecutionApiResultQueryIdResource [[deprecated]] = ExecutionApiResources::ResultQueryIdResource;
using ExecutionApiQueryResource [[deprecated]] = ExecutionApiResources::QueryResource;

//
// The restbed service to actually implement the REST server
//
class  ExecutionApi
{
public:
    explicit ExecutionApi(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~ExecutionApi();

    std::shared_ptr<ExecutionApiResources::QueriesResource> getQueriesResource();
    std::shared_ptr<ExecutionApiResources::QueryQueryIdResource> getQueryQueryIdResource();
    std::shared_ptr<ExecutionApiResources::ErrorQueryIdResource> getErrorQueryIdResource();
    std::shared_ptr<ExecutionApiResources::ResultQueryIdResource> getResultQueryIdResource();
    std::shared_ptr<ExecutionApiResources::QueryResource> getQueryResource();

    void setResource(std::shared_ptr<ExecutionApiResources::QueriesResource> resource);
    void setResource(std::shared_ptr<ExecutionApiResources::QueryQueryIdResource> resource);
    void setResource(std::shared_ptr<ExecutionApiResources::ErrorQueryIdResource> resource);
    void setResource(std::shared_ptr<ExecutionApiResources::ResultQueryIdResource> resource);
    void setResource(std::shared_ptr<ExecutionApiResources::QueryResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setExecutionApiQueriesResource(std::shared_ptr<ExecutionApiResources::QueriesResource> spExecutionApiQueriesResource);
    [[deprecated("use setResource()")]]
    virtual void setExecutionApiQueryQueryIdResource(std::shared_ptr<ExecutionApiResources::QueryQueryIdResource> spExecutionApiQueryQueryIdResource);
    [[deprecated("use setResource()")]]
    virtual void setExecutionApiErrorQueryIdResource(std::shared_ptr<ExecutionApiResources::ErrorQueryIdResource> spExecutionApiErrorQueryIdResource);
    [[deprecated("use setResource()")]]
    virtual void setExecutionApiResultQueryIdResource(std::shared_ptr<ExecutionApiResources::ResultQueryIdResource> spExecutionApiResultQueryIdResource);
    [[deprecated("use setResource()")]]
    virtual void setExecutionApiQueryResource(std::shared_ptr<ExecutionApiResources::QueryResource> spExecutionApiQueryResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<ExecutionApiResources::QueriesResource> m_spQueriesResource;
    std::shared_ptr<ExecutionApiResources::QueryQueryIdResource> m_spQueryQueryIdResource;
    std::shared_ptr<ExecutionApiResources::ErrorQueryIdResource> m_spErrorQueryIdResource;
    std::shared_ptr<ExecutionApiResources::ResultQueryIdResource> m_spResultQueryIdResource;
    std::shared_ptr<ExecutionApiResources::QueryResource> m_spQueryResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* ExecutionApi_H_ */

