/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MetadataApi.h
 *
 * 
 */

#ifndef MetadataApi_H_
#define MetadataApi_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "SystemInformation.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  MetadataApiException: public std::exception
{
public:
    MetadataApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace MetadataApiResources {
/// <summary>
/// Get basic information about the system (e.g. version, uptime, etc.)
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  SystemInfoResource: public restbed::Resource
{
public:
    SystemInfoResource(const std::string& context = "");
    virtual ~SystemInfoResource() = default;

    SystemInfoResource(
        const SystemInfoResource& other) = default; // copy constructor
    SystemInfoResource(SystemInfoResource&& other) noexcept = default; // move constructor

    SystemInfoResource& operator=(const SystemInfoResource& other) = default; // copy assignment
    SystemInfoResource& operator=(SystemInfoResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, SystemInformation>(
        )> handler_GET_func =
            []() -> std::pair<int, SystemInformation>
                { throw MetadataApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, SystemInformation> handler_GET(
        );


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleMetadataApiException(const MetadataApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace MetadataApiResources */

using MetadataApiSystemInfoResource [[deprecated]] = MetadataApiResources::SystemInfoResource;

//
// The restbed service to actually implement the REST server
//
class  MetadataApi
{
public:
    explicit MetadataApi(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~MetadataApi();

    std::shared_ptr<MetadataApiResources::SystemInfoResource> getSystemInfoResource();

    void setResource(std::shared_ptr<MetadataApiResources::SystemInfoResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setMetadataApiSystemInfoResource(std::shared_ptr<MetadataApiResources::SystemInfoResource> spMetadataApiSystemInfoResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<MetadataApiResources::SystemInfoResource> m_spSystemInfoResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* MetadataApi_H_ */

