/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Proj3Api.h
 *
 * 
 */

#ifndef Proj3Api_H_
#define Proj3Api_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "Error.h"
#include "ExecuteQueryRequest.h"
#include "GetQueryResult_request.h"
#include "MultipleProblemsError.h"
#include "Query.h"
#include "QueryResult_inner.h"
#include "ShallowQuery.h"
#include "ShallowTable.h"
#include "SystemInformation.h"
#include "TableSchema.h"
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  Proj3ApiException: public std::exception
{
public:
    Proj3ApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace Proj3ApiResources {
/// <summary>
/// Create new table in database
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  TableResource: public restbed::Resource
{
public:
    TableResource(const std::string& context = "");
    virtual ~TableResource() = default;

    TableResource(
        const TableResource& other) = default; // copy constructor
    TableResource(TableResource&& other) noexcept = default; // move constructor

    TableResource& operator=(const TableResource& other) = default; // copy assignment
    TableResource& operator=(TableResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::string>(
        TableSchema & tableSchema)> handler_PUT_func =
            [](TableSchema &) -> std::pair<int, std::string>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::string> handler_PUT(
        TableSchema & tableSchema);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_PUT_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Delete selected table from database
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  TableTableIdResource: public restbed::Resource
{
public:
    TableTableIdResource(const std::string& context = "");
    virtual ~TableTableIdResource() = default;

    TableTableIdResource(
        const TableTableIdResource& other) = default; // copy constructor
    TableTableIdResource(TableTableIdResource&& other) noexcept = default; // move constructor

    TableTableIdResource& operator=(const TableTableIdResource& other) = default; // copy assignment
    TableTableIdResource& operator=(TableTableIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<int(
        std::string & tableId)> handler_DELETE_func =
            [](std::string &) -> int
                { throw Proj3ApiException(501, "Not implemented"); };

    std::function<std::pair<int, TableSchema>(
        std::string & tableId)> handler_GET_func =
            [](std::string &) -> std::pair<int, TableSchema>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual int handler_DELETE(
        std::string & tableId);

    virtual std::pair<int, TableSchema> handler_GET(
        std::string & tableId);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_DELETE_internal(const std::shared_ptr<restbed::Session> session);
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get list of queries (optional in project 3, but useful). Use those IDs to get details by calling /query endpoint.
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  QueriesResource: public restbed::Resource
{
public:
    QueriesResource(const std::string& context = "");
    virtual ~QueriesResource() = default;

    QueriesResource(
        const QueriesResource& other) = default; // copy constructor
    QueriesResource(QueriesResource&& other) noexcept = default; // move constructor

    QueriesResource& operator=(const QueriesResource& other) = default; // copy assignment
    QueriesResource& operator=(QueriesResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::vector<ShallowQuery>>(
        )> handler_GET_func =
            []() -> std::pair<int, std::vector<ShallowQuery>>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::vector<ShallowQuery>> handler_GET(
        );


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get detailed status of selected query
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  QueryQueryIdResource: public restbed::Resource
{
public:
    QueryQueryIdResource(const std::string& context = "");
    virtual ~QueryQueryIdResource() = default;

    QueryQueryIdResource(
        const QueryQueryIdResource& other) = default; // copy constructor
    QueryQueryIdResource(QueryQueryIdResource&& other) noexcept = default; // move constructor

    QueryQueryIdResource& operator=(const QueryQueryIdResource& other) = default; // copy assignment
    QueryQueryIdResource& operator=(QueryQueryIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, Query>(
        std::string & queryId)> handler_GET_func =
            [](std::string &) -> std::pair<int, Query>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, Query> handler_GET(
        std::string & queryId);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get error of selected query (will be available only for queries in FAILED state)
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  ErrorQueryIdResource: public restbed::Resource
{
public:
    ErrorQueryIdResource(const std::string& context = "");
    virtual ~ErrorQueryIdResource() = default;

    ErrorQueryIdResource(
        const ErrorQueryIdResource& other) = default; // copy constructor
    ErrorQueryIdResource(ErrorQueryIdResource&& other) noexcept = default; // move constructor

    ErrorQueryIdResource& operator=(const ErrorQueryIdResource& other) = default; // copy assignment
    ErrorQueryIdResource& operator=(ErrorQueryIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, MultipleProblemsError>(
        std::string & queryId)> handler_GET_func =
            [](std::string &) -> std::pair<int, MultipleProblemsError>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, MultipleProblemsError> handler_GET(
        std::string & queryId);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get result of selected query (will be available only for SELECT queries after they are completed)
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  ResultQueryIdResource: public restbed::Resource
{
public:
    ResultQueryIdResource(const std::string& context = "");
    virtual ~ResultQueryIdResource() = default;

    ResultQueryIdResource(
        const ResultQueryIdResource& other) = default; // copy constructor
    ResultQueryIdResource(ResultQueryIdResource&& other) noexcept = default; // move constructor

    ResultQueryIdResource& operator=(const ResultQueryIdResource& other) = default; // copy assignment
    ResultQueryIdResource& operator=(ResultQueryIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::vector<QueryResult_inner>>(
        std::string & queryId, GetQueryResult_request & getQueryResultRequest)> handler_GET_func =
            [](std::string &, GetQueryResult_request &) -> std::pair<int, std::vector<QueryResult_inner>>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::vector<QueryResult_inner>> handler_GET(
        std::string & queryId, GetQueryResult_request & getQueryResultRequest);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get basic information about the system (e.g. version, uptime, etc.)
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  SystemInfoResource: public restbed::Resource
{
public:
    SystemInfoResource(const std::string& context = "");
    virtual ~SystemInfoResource() = default;

    SystemInfoResource(
        const SystemInfoResource& other) = default; // copy constructor
    SystemInfoResource(SystemInfoResource&& other) noexcept = default; // move constructor

    SystemInfoResource& operator=(const SystemInfoResource& other) = default; // copy assignment
    SystemInfoResource& operator=(SystemInfoResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, SystemInformation>(
        )> handler_GET_func =
            []() -> std::pair<int, SystemInformation>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, SystemInformation> handler_GET(
        );


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get list of tables with their accompaning IDs. Use those IDs to get details by calling /table endpoint.
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  TablesResource: public restbed::Resource
{
public:
    TablesResource(const std::string& context = "");
    virtual ~TablesResource() = default;

    TablesResource(
        const TablesResource& other) = default; // copy constructor
    TablesResource(TablesResource&& other) noexcept = default; // move constructor

    TablesResource& operator=(const TablesResource& other) = default; // copy assignment
    TablesResource& operator=(TablesResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::vector<ShallowTable>>(
        )> handler_GET_func =
            []() -> std::pair<int, std::vector<ShallowTable>>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::vector<ShallowTable>> handler_GET(
        );


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Submit new query for execution
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  QueryResource: public restbed::Resource
{
public:
    QueryResource(const std::string& context = "");
    virtual ~QueryResource() = default;

    QueryResource(
        const QueryResource& other) = default; // copy constructor
    QueryResource(QueryResource&& other) noexcept = default; // move constructor

    QueryResource& operator=(const QueryResource& other) = default; // copy assignment
    QueryResource& operator=(QueryResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::string>(
        ExecuteQueryRequest & executeQueryRequest)> handler_POST_func =
            [](ExecuteQueryRequest &) -> std::pair<int, std::string>
                { throw Proj3ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::string> handler_POST(
        ExecuteQueryRequest & executeQueryRequest);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj3ApiException(const Proj3ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_POST_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace Proj3ApiResources */

using Proj3ApiTableResource [[deprecated]] = Proj3ApiResources::TableResource;
using Proj3ApiTableTableIdResource [[deprecated]] = Proj3ApiResources::TableTableIdResource;
using Proj3ApiQueriesResource [[deprecated]] = Proj3ApiResources::QueriesResource;
using Proj3ApiQueryQueryIdResource [[deprecated]] = Proj3ApiResources::QueryQueryIdResource;
using Proj3ApiErrorQueryIdResource [[deprecated]] = Proj3ApiResources::ErrorQueryIdResource;
using Proj3ApiResultQueryIdResource [[deprecated]] = Proj3ApiResources::ResultQueryIdResource;
using Proj3ApiSystemInfoResource [[deprecated]] = Proj3ApiResources::SystemInfoResource;
using Proj3ApiTablesResource [[deprecated]] = Proj3ApiResources::TablesResource;
using Proj3ApiQueryResource [[deprecated]] = Proj3ApiResources::QueryResource;

//
// The restbed service to actually implement the REST server
//
class  Proj3Api
{
public:
    explicit Proj3Api(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~Proj3Api();

    std::shared_ptr<Proj3ApiResources::TableResource> getTableResource();
    std::shared_ptr<Proj3ApiResources::TableTableIdResource> getTableTableIdResource();
    std::shared_ptr<Proj3ApiResources::QueriesResource> getQueriesResource();
    std::shared_ptr<Proj3ApiResources::QueryQueryIdResource> getQueryQueryIdResource();
    std::shared_ptr<Proj3ApiResources::ErrorQueryIdResource> getErrorQueryIdResource();
    std::shared_ptr<Proj3ApiResources::ResultQueryIdResource> getResultQueryIdResource();
    std::shared_ptr<Proj3ApiResources::SystemInfoResource> getSystemInfoResource();
    std::shared_ptr<Proj3ApiResources::TablesResource> getTablesResource();
    std::shared_ptr<Proj3ApiResources::QueryResource> getQueryResource();

    void setResource(std::shared_ptr<Proj3ApiResources::TableResource> resource);
    void setResource(std::shared_ptr<Proj3ApiResources::TableTableIdResource> resource);
    void setResource(std::shared_ptr<Proj3ApiResources::QueriesResource> resource);
    void setResource(std::shared_ptr<Proj3ApiResources::QueryQueryIdResource> resource);
    void setResource(std::shared_ptr<Proj3ApiResources::ErrorQueryIdResource> resource);
    void setResource(std::shared_ptr<Proj3ApiResources::ResultQueryIdResource> resource);
    void setResource(std::shared_ptr<Proj3ApiResources::SystemInfoResource> resource);
    void setResource(std::shared_ptr<Proj3ApiResources::TablesResource> resource);
    void setResource(std::shared_ptr<Proj3ApiResources::QueryResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiTableResource(std::shared_ptr<Proj3ApiResources::TableResource> spProj3ApiTableResource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiTableTableIdResource(std::shared_ptr<Proj3ApiResources::TableTableIdResource> spProj3ApiTableTableIdResource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiQueriesResource(std::shared_ptr<Proj3ApiResources::QueriesResource> spProj3ApiQueriesResource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiQueryQueryIdResource(std::shared_ptr<Proj3ApiResources::QueryQueryIdResource> spProj3ApiQueryQueryIdResource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiErrorQueryIdResource(std::shared_ptr<Proj3ApiResources::ErrorQueryIdResource> spProj3ApiErrorQueryIdResource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiResultQueryIdResource(std::shared_ptr<Proj3ApiResources::ResultQueryIdResource> spProj3ApiResultQueryIdResource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiSystemInfoResource(std::shared_ptr<Proj3ApiResources::SystemInfoResource> spProj3ApiSystemInfoResource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiTablesResource(std::shared_ptr<Proj3ApiResources::TablesResource> spProj3ApiTablesResource);
    [[deprecated("use setResource()")]]
    virtual void setProj3ApiQueryResource(std::shared_ptr<Proj3ApiResources::QueryResource> spProj3ApiQueryResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<Proj3ApiResources::TableResource> m_spTableResource;
    std::shared_ptr<Proj3ApiResources::TableTableIdResource> m_spTableTableIdResource;
    std::shared_ptr<Proj3ApiResources::QueriesResource> m_spQueriesResource;
    std::shared_ptr<Proj3ApiResources::QueryQueryIdResource> m_spQueryQueryIdResource;
    std::shared_ptr<Proj3ApiResources::ErrorQueryIdResource> m_spErrorQueryIdResource;
    std::shared_ptr<Proj3ApiResources::ResultQueryIdResource> m_spResultQueryIdResource;
    std::shared_ptr<Proj3ApiResources::SystemInfoResource> m_spSystemInfoResource;
    std::shared_ptr<Proj3ApiResources::TablesResource> m_spTablesResource;
    std::shared_ptr<Proj3ApiResources::QueryResource> m_spQueryResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* Proj3Api_H_ */

