/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/uri.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>

#include "Proj3Api.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

namespace {
[[maybe_unused]]
std::string selectPreferredContentType(const std::vector<std::string>& contentTypes) {
    if (contentTypes.size() == 0) {
        return "application/json";
    }

    if (contentTypes.size() == 1) {
        return contentTypes.at(0);
    }

    static const std::array<std::string, 2> preferredTypes = {"json", "xml"};
    for (const auto& preferredType: preferredTypes) {
        const auto ret = std::find_if(contentTypes.cbegin(),
        contentTypes.cend(),
        [preferredType](const std::string& str) {
            return str.find(preferredType) != std::string::npos;});
        if (ret != contentTypes.cend()) {
            return *ret;
        }
    }

    return contentTypes.at(0);
}
}

Proj3ApiException::Proj3ApiException(int status_code, std::string what)
  : m_status(status_code),
    m_what(what)
{

}
int Proj3ApiException::getStatus() const
{
    return m_status;
}
const char* Proj3ApiException::what() const noexcept
{
    return m_what.c_str();
}


template<class MODEL_T>
MODEL_T extractJsonModelBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto model = MODEL_T(pt);
    return model;
}

template<class MODEL_T>
std::vector<MODEL_T> extractJsonArrayBodyParam(const std::string& bodyContent)
{
    std::stringstream sstream(bodyContent);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream, pt);

    auto arrayRet = std::vector<MODEL_T>();
    for (const auto& child: pt) {
        arrayRet.emplace_back(MODEL_T(child.second));
    }
    return arrayRet;
}

template <class KEY_T, class VAL_T>
std::string convertMapResponse(const std::map<KEY_T, VAL_T>& map)
{
    boost::property_tree::ptree pt;
    for(const auto &kv: map) {
    pt.push_back(boost::property_tree::ptree::value_type(
        boost::lexical_cast<std::string>(kv.first),
        boost::property_tree::ptree(
        boost::lexical_cast<std::string>(kv.second))));
    }
    std::stringstream sstream;
    write_json(sstream, pt);
    std::string result = sstream.str();
    return result;
}

namespace Proj3ApiResources {
TableResource::TableResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/table");
	this->set_method_handler("PUT",
		std::bind(&TableResource::handler_PUT_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> TableResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> TableResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> TableResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void TableResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void TableResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void TableResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void TableResource::handler_PUT_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto tableSchema = extractJsonModelBodyParam<TableSchema>(bodyContent);
    
    int status_code = 500;
    std::string resultObject = "";
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_PUT(tableSchema);
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
        "application/json, "
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject;
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Response used when more problems can occur in the system when processing request";
    
        result = resultObject.toJsonString();
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, std::string> TableResource::handler_PUT(
        TableSchema & tableSchema)
{
    return handler_PUT_func(tableSchema);
}


std::string TableResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string TableResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
TableTableIdResource::TableTableIdResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/table/{tableId: .*}");
	this->set_method_handler("DELETE",
		std::bind(&TableTableIdResource::handler_DELETE_internal, this,
			std::placeholders::_1));
	this->set_method_handler("GET",
		std::bind(&TableTableIdResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> TableTableIdResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> TableTableIdResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> TableTableIdResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void TableTableIdResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void TableTableIdResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void TableTableIdResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void TableTableIdResource::handler_DELETE_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // Getting the path params
    std::string tableId = request->get_path_parameter("tableId", "");
    
    int status_code = 500;
    std::string result = "";
    
    try {
        status_code =
            handler_DELETE(tableId);
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}

// x-extension
void TableTableIdResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session) {
    const auto request = session->get_request();
    // Getting the path params
    std::string tableId = request->get_path_parameter("tableId", "");
    
    int status_code = 500;
    TableSchema resultObject = TableSchema{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(tableId);
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}

int TableTableIdResource::handler_DELETE(
        std::string & tableId)
{
    return handler_DELETE_func(tableId);
}

std::pair<int, TableSchema> TableTableIdResource::handler_GET(
    std::string & tableId)
{
    return handler_GET_func(tableId);
}

std::string TableTableIdResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string TableTableIdResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
QueriesResource::QueriesResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/queries");
	this->set_method_handler("GET",
		std::bind(&QueriesResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> QueriesResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> QueriesResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> QueriesResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void QueriesResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void QueriesResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void QueriesResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void QueriesResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    
    int status_code = 500;
    std::vector<ShallowQuery> resultObject = std::vector<ShallowQuery>();
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET();
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, std::vector<ShallowQuery>> QueriesResource::handler_GET(
        )
{
    return handler_GET_func();
}


std::string QueriesResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string QueriesResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
QueryQueryIdResource::QueryQueryIdResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/query/{queryId: .*}");
	this->set_method_handler("GET",
		std::bind(&QueryQueryIdResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> QueryQueryIdResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> QueryQueryIdResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> QueryQueryIdResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void QueryQueryIdResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void QueryQueryIdResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void QueryQueryIdResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void QueryQueryIdResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // Getting the path params
    std::string queryId = request->get_path_parameter("queryId", "");
    
    int status_code = 500;
    Query resultObject = Query{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(queryId);
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, Query> QueryQueryIdResource::handler_GET(
        std::string & queryId)
{
    return handler_GET_func(queryId);
}


std::string QueryQueryIdResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string QueryQueryIdResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
ErrorQueryIdResource::ErrorQueryIdResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/error/{queryId: .*}");
	this->set_method_handler("GET",
		std::bind(&ErrorQueryIdResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> ErrorQueryIdResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> ErrorQueryIdResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> ErrorQueryIdResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void ErrorQueryIdResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void ErrorQueryIdResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void ErrorQueryIdResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void ErrorQueryIdResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // Getting the path params
    std::string queryId = request->get_path_parameter("queryId", "");
    
    int status_code = 500;
    MultipleProblemsError resultObject = MultipleProblemsError{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(queryId);
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, MultipleProblemsError> ErrorQueryIdResource::handler_GET(
        std::string & queryId)
{
    return handler_GET_func(queryId);
}


std::string ErrorQueryIdResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string ErrorQueryIdResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
ResultQueryIdResource::ResultQueryIdResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/result/{queryId: .*}");
	this->set_method_handler("GET",
		std::bind(&ResultQueryIdResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> ResultQueryIdResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> ResultQueryIdResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> ResultQueryIdResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void ResultQueryIdResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void ResultQueryIdResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void ResultQueryIdResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void ResultQueryIdResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto getQueryResultRequest = extractJsonModelBodyParam<GetQueryResult_request>(bodyContent);
    // Getting the path params
    std::string queryId = request->get_path_parameter("queryId", "");
    
    int status_code = 500;
    std::vector<QueryResult_inner> resultObject = std::vector<QueryResult_inner>();
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET(queryId, getQueryResultRequest);
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
        "application/json, "
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 404) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 404, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Generic error";
    
        result = resultObject.toJsonString();
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, std::vector<QueryResult_inner>> ResultQueryIdResource::handler_GET(
        std::string & queryId, GetQueryResult_request & getQueryResultRequest)
{
    return handler_GET_func(queryId, getQueryResultRequest);
}


std::string ResultQueryIdResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string ResultQueryIdResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
SystemInfoResource::SystemInfoResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/system/info");
	this->set_method_handler("GET",
		std::bind(&SystemInfoResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> SystemInfoResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> SystemInfoResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> SystemInfoResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void SystemInfoResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void SystemInfoResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void SystemInfoResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void SystemInfoResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    
    int status_code = 500;
    SystemInformation resultObject = SystemInformation{};
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET();
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject.toJsonString();
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, SystemInformation> SystemInfoResource::handler_GET(
        )
{
    return handler_GET_func();
}


std::string SystemInfoResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string SystemInfoResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
TablesResource::TablesResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/tables");
	this->set_method_handler("GET",
		std::bind(&TablesResource::handler_GET_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> TablesResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> TablesResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> TablesResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void TablesResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void TablesResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void TablesResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void TablesResource::handler_GET_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    
    int status_code = 500;
    std::vector<ShallowTable> resultObject = std::vector<ShallowTable>();
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_GET();
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, std::vector<ShallowTable>> TablesResource::handler_GET(
        )
{
    return handler_GET_func();
}


std::string TablesResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string TablesResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}
QueryResource::QueryResource(const std::string& context /* = "" */)
{
	this->set_path(context + "/query");
	this->set_method_handler("POST",
		std::bind(&QueryResource::handler_POST_internal, this,
			std::placeholders::_1));
}

std::pair<int, std::string> QueryResource::handleProj3ApiException(const Proj3ApiException& e)
{
    return std::make_pair<int, std::string>(e.getStatus(), e.what());
}

std::pair<int, std::string> QueryResource::handleStdException(const std::exception& e)
{
    return std::make_pair<int, std::string>(500, e.what());
}

std::pair<int, std::string> QueryResource::handleUnspecifiedException()
{
    return std::make_pair<int, std::string>(500, "Unknown exception occurred");
}

void QueryResource::setResponseHeader(const std::shared_ptr<restbed::Session>& session, const std::string& header)
{
    session->set_header(header, "");
}

void QueryResource::returnResponse(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result, std::multimap<std::string, std::string>& responseHeaders)
{
    responseHeaders.insert(std::make_pair("Connection", "close"));
    session->close(status, result, responseHeaders);
}

void QueryResource::defaultSessionClose(const std::shared_ptr<restbed::Session>& session, const int status, const std::string& result)
{
    session->close(status, result, { {"Connection", "close"} });
}

void QueryResource::handler_POST_internal(const std::shared_ptr<restbed::Session> session)
{
    const auto request = session->get_request();
    // body params or form params here from the body content string
    std::string bodyContent = extractBodyContent(session);
    auto executeQueryRequest = extractJsonModelBodyParam<ExecuteQueryRequest>(bodyContent);
    
    int status_code = 500;
    std::string resultObject = "";
    std::string result = "";
    
    try {
        std::tie(status_code, resultObject) =
            handler_POST(executeQueryRequest);
    }
    catch(const Proj3ApiException& e) {
        std::tie(status_code, result) = handleProj3ApiException(e);
    }
    catch(const std::exception& e) {
        std::tie(status_code, result) = handleStdException(e);
    }
    catch(...) {
        std::tie(status_code, result) = handleUnspecifiedException();
    }
    
    std::multimap< std::string, std::string > responseHeaders {};
    static const std::vector<std::string> contentTypes{
        "application/json",
    };
    static const std::string acceptTypes{
        "application/json, "
    };
    
    if (status_code == 200) {
        responseHeaders.insert(std::make_pair("Content-Type", selectPreferredContentType(contentTypes)));
        if (!acceptTypes.empty()) {
            responseHeaders.insert(std::make_pair("Accept", acceptTypes));
        }
    
        result = resultObject;
        returnResponse(session, 200, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    if (status_code == 400) {
        responseHeaders.insert(std::make_pair("Content-Type", "text/plain"));
        result = "Response used when more problems can occur in the system when processing request";
    
        result = resultObject.toJsonString();
        returnResponse(session, 400, result.empty() ? "{}" : result, responseHeaders);
        return;
    }
    defaultSessionClose(session, status_code, result);
    
    
}


std::pair<int, std::string> QueryResource::handler_POST(
        ExecuteQueryRequest & executeQueryRequest)
{
    return handler_POST_func(executeQueryRequest);
}


std::string QueryResource::extractBodyContent(const std::shared_ptr<restbed::Session>& session) {
  const auto request = session->get_request();
  int content_length = request->get_header("Content-Length", 0);
  std::string bodyContent;
  session->fetch(content_length,
                 [&bodyContent](const std::shared_ptr<restbed::Session> session,
                                const restbed::Bytes &body) {
                   bodyContent = restbed::String::format(
                       "%.*s\n", (int)body.size(), body.data());
                 });
  return bodyContent;
}

std::string QueryResource::extractFormParamsFromBody(const std::string& paramName, const std::string& body) {
    const auto uri = restbed::Uri("urlencoded?" + body, true);
    const auto params = uri.get_query_parameters();
    const auto result = params.find(paramName);
    if (result != params.cend()) {
        return result->second;
    }
    return "";
}

} /* namespace Proj3ApiResources */

Proj3Api::Proj3Api(std::shared_ptr<restbed::Service> const& restbedService)
: m_service(restbedService)
{
}

Proj3Api::~Proj3Api() {}

std::shared_ptr<Proj3ApiResources::TableResource> Proj3Api::getTableResource() {
    if (!m_spTableResource) {
        setResource(std::make_shared<Proj3ApiResources::TableResource>());
    }
    return m_spTableResource;
}
std::shared_ptr<Proj3ApiResources::TableTableIdResource> Proj3Api::getTableTableIdResource() {
    if (!m_spTableTableIdResource) {
        setResource(std::make_shared<Proj3ApiResources::TableTableIdResource>());
    }
    return m_spTableTableIdResource;
}
std::shared_ptr<Proj3ApiResources::QueriesResource> Proj3Api::getQueriesResource() {
    if (!m_spQueriesResource) {
        setResource(std::make_shared<Proj3ApiResources::QueriesResource>());
    }
    return m_spQueriesResource;
}
std::shared_ptr<Proj3ApiResources::QueryQueryIdResource> Proj3Api::getQueryQueryIdResource() {
    if (!m_spQueryQueryIdResource) {
        setResource(std::make_shared<Proj3ApiResources::QueryQueryIdResource>());
    }
    return m_spQueryQueryIdResource;
}
std::shared_ptr<Proj3ApiResources::ErrorQueryIdResource> Proj3Api::getErrorQueryIdResource() {
    if (!m_spErrorQueryIdResource) {
        setResource(std::make_shared<Proj3ApiResources::ErrorQueryIdResource>());
    }
    return m_spErrorQueryIdResource;
}
std::shared_ptr<Proj3ApiResources::ResultQueryIdResource> Proj3Api::getResultQueryIdResource() {
    if (!m_spResultQueryIdResource) {
        setResource(std::make_shared<Proj3ApiResources::ResultQueryIdResource>());
    }
    return m_spResultQueryIdResource;
}
std::shared_ptr<Proj3ApiResources::SystemInfoResource> Proj3Api::getSystemInfoResource() {
    if (!m_spSystemInfoResource) {
        setResource(std::make_shared<Proj3ApiResources::SystemInfoResource>());
    }
    return m_spSystemInfoResource;
}
std::shared_ptr<Proj3ApiResources::TablesResource> Proj3Api::getTablesResource() {
    if (!m_spTablesResource) {
        setResource(std::make_shared<Proj3ApiResources::TablesResource>());
    }
    return m_spTablesResource;
}
std::shared_ptr<Proj3ApiResources::QueryResource> Proj3Api::getQueryResource() {
    if (!m_spQueryResource) {
        setResource(std::make_shared<Proj3ApiResources::QueryResource>());
    }
    return m_spQueryResource;
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::TableResource> resource) {
    m_spTableResource = resource;
    m_service->publish(m_spTableResource);
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::TableTableIdResource> resource) {
    m_spTableTableIdResource = resource;
    m_service->publish(m_spTableTableIdResource);
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::QueriesResource> resource) {
    m_spQueriesResource = resource;
    m_service->publish(m_spQueriesResource);
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::QueryQueryIdResource> resource) {
    m_spQueryQueryIdResource = resource;
    m_service->publish(m_spQueryQueryIdResource);
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::ErrorQueryIdResource> resource) {
    m_spErrorQueryIdResource = resource;
    m_service->publish(m_spErrorQueryIdResource);
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::ResultQueryIdResource> resource) {
    m_spResultQueryIdResource = resource;
    m_service->publish(m_spResultQueryIdResource);
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::SystemInfoResource> resource) {
    m_spSystemInfoResource = resource;
    m_service->publish(m_spSystemInfoResource);
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::TablesResource> resource) {
    m_spTablesResource = resource;
    m_service->publish(m_spTablesResource);
}
void Proj3Api::setResource(std::shared_ptr<Proj3ApiResources::QueryResource> resource) {
    m_spQueryResource = resource;
    m_service->publish(m_spQueryResource);
}
void Proj3Api::setProj3ApiTableResource(std::shared_ptr<Proj3ApiResources::TableResource> spTableResource) {
    m_spTableResource = spTableResource;
    m_service->publish(m_spTableResource);
}
void Proj3Api::setProj3ApiTableTableIdResource(std::shared_ptr<Proj3ApiResources::TableTableIdResource> spTableTableIdResource) {
    m_spTableTableIdResource = spTableTableIdResource;
    m_service->publish(m_spTableTableIdResource);
}
void Proj3Api::setProj3ApiQueriesResource(std::shared_ptr<Proj3ApiResources::QueriesResource> spQueriesResource) {
    m_spQueriesResource = spQueriesResource;
    m_service->publish(m_spQueriesResource);
}
void Proj3Api::setProj3ApiQueryQueryIdResource(std::shared_ptr<Proj3ApiResources::QueryQueryIdResource> spQueryQueryIdResource) {
    m_spQueryQueryIdResource = spQueryQueryIdResource;
    m_service->publish(m_spQueryQueryIdResource);
}
void Proj3Api::setProj3ApiErrorQueryIdResource(std::shared_ptr<Proj3ApiResources::ErrorQueryIdResource> spErrorQueryIdResource) {
    m_spErrorQueryIdResource = spErrorQueryIdResource;
    m_service->publish(m_spErrorQueryIdResource);
}
void Proj3Api::setProj3ApiResultQueryIdResource(std::shared_ptr<Proj3ApiResources::ResultQueryIdResource> spResultQueryIdResource) {
    m_spResultQueryIdResource = spResultQueryIdResource;
    m_service->publish(m_spResultQueryIdResource);
}
void Proj3Api::setProj3ApiSystemInfoResource(std::shared_ptr<Proj3ApiResources::SystemInfoResource> spSystemInfoResource) {
    m_spSystemInfoResource = spSystemInfoResource;
    m_service->publish(m_spSystemInfoResource);
}
void Proj3Api::setProj3ApiTablesResource(std::shared_ptr<Proj3ApiResources::TablesResource> spTablesResource) {
    m_spTablesResource = spTablesResource;
    m_service->publish(m_spTablesResource);
}
void Proj3Api::setProj3ApiQueryResource(std::shared_ptr<Proj3ApiResources::QueryResource> spQueryResource) {
    m_spQueryResource = spQueryResource;
    m_service->publish(m_spQueryResource);
}


void Proj3Api::publishDefaultResources() {
    if (!m_spTableResource) {
        setResource(std::make_shared<Proj3ApiResources::TableResource>());
    }
    if (!m_spTableTableIdResource) {
        setResource(std::make_shared<Proj3ApiResources::TableTableIdResource>());
    }
    if (!m_spQueriesResource) {
        setResource(std::make_shared<Proj3ApiResources::QueriesResource>());
    }
    if (!m_spQueryQueryIdResource) {
        setResource(std::make_shared<Proj3ApiResources::QueryQueryIdResource>());
    }
    if (!m_spErrorQueryIdResource) {
        setResource(std::make_shared<Proj3ApiResources::ErrorQueryIdResource>());
    }
    if (!m_spResultQueryIdResource) {
        setResource(std::make_shared<Proj3ApiResources::ResultQueryIdResource>());
    }
    if (!m_spSystemInfoResource) {
        setResource(std::make_shared<Proj3ApiResources::SystemInfoResource>());
    }
    if (!m_spTablesResource) {
        setResource(std::make_shared<Proj3ApiResources::TablesResource>());
    }
    if (!m_spQueryResource) {
        setResource(std::make_shared<Proj3ApiResources::QueryResource>());
    }
}

std::shared_ptr<restbed::Service> Proj3Api::service() {
    return m_service;
}


}
}
}
}

