/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Proj4Api.h
 *
 * 
 */

#ifndef Proj4Api_H_
#define Proj4Api_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "ShallowQuery.h"
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  Proj4ApiException: public std::exception
{
public:
    Proj4ApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace Proj4ApiResources {
/// <summary>
/// Get list of queries (optional in project 3, but useful). Use those IDs to get details by calling /query endpoint.
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  QueriesResource: public restbed::Resource
{
public:
    QueriesResource(const std::string& context = "");
    virtual ~QueriesResource() = default;

    QueriesResource(
        const QueriesResource& other) = default; // copy constructor
    QueriesResource(QueriesResource&& other) noexcept = default; // move constructor

    QueriesResource& operator=(const QueriesResource& other) = default; // copy assignment
    QueriesResource& operator=(QueriesResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::vector<ShallowQuery>>(
        )> handler_GET_func =
            []() -> std::pair<int, std::vector<ShallowQuery>>
                { throw Proj4ApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::vector<ShallowQuery>> handler_GET(
        );


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleProj4ApiException(const Proj4ApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace Proj4ApiResources */

using Proj4ApiQueriesResource [[deprecated]] = Proj4ApiResources::QueriesResource;

//
// The restbed service to actually implement the REST server
//
class  Proj4Api
{
public:
    explicit Proj4Api(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~Proj4Api();

    std::shared_ptr<Proj4ApiResources::QueriesResource> getQueriesResource();

    void setResource(std::shared_ptr<Proj4ApiResources::QueriesResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setProj4ApiQueriesResource(std::shared_ptr<Proj4ApiResources::QueriesResource> spProj4ApiQueriesResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<Proj4ApiResources::QueriesResource> m_spQueriesResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* Proj4Api_H_ */

