/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SchemaApi.h
 *
 * 
 */

#ifndef SchemaApi_H_
#define SchemaApi_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "Error.h"
#include "MultipleProblemsError.h"
#include "ShallowTable.h"
#include "TableSchema.h"
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  SchemaApiException: public std::exception
{
public:
    SchemaApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace SchemaApiResources {
/// <summary>
/// Create new table in database
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  TableResource: public restbed::Resource
{
public:
    TableResource(const std::string& context = "");
    virtual ~TableResource() = default;

    TableResource(
        const TableResource& other) = default; // copy constructor
    TableResource(TableResource&& other) noexcept = default; // move constructor

    TableResource& operator=(const TableResource& other) = default; // copy assignment
    TableResource& operator=(TableResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::string>(
        TableSchema & tableSchema)> handler_PUT_func =
            [](TableSchema &) -> std::pair<int, std::string>
                { throw SchemaApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::string> handler_PUT(
        TableSchema & tableSchema);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleSchemaApiException(const SchemaApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_PUT_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Delete selected table from database
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  TableTableIdResource: public restbed::Resource
{
public:
    TableTableIdResource(const std::string& context = "");
    virtual ~TableTableIdResource() = default;

    TableTableIdResource(
        const TableTableIdResource& other) = default; // copy constructor
    TableTableIdResource(TableTableIdResource&& other) noexcept = default; // move constructor

    TableTableIdResource& operator=(const TableTableIdResource& other) = default; // copy assignment
    TableTableIdResource& operator=(TableTableIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<int(
        std::string & tableId)> handler_DELETE_func =
            [](std::string &) -> int
                { throw SchemaApiException(501, "Not implemented"); };

    std::function<std::pair<int, TableSchema>(
        std::string & tableId)> handler_GET_func =
            [](std::string &) -> std::pair<int, TableSchema>
                { throw SchemaApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual int handler_DELETE(
        std::string & tableId);

    virtual std::pair<int, TableSchema> handler_GET(
        std::string & tableId);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleSchemaApiException(const SchemaApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_DELETE_internal(const std::shared_ptr<restbed::Session> session);
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

/// <summary>
/// Get list of tables with their accompaning IDs. Use those IDs to get details by calling /table endpoint.
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  TablesResource: public restbed::Resource
{
public:
    TablesResource(const std::string& context = "");
    virtual ~TablesResource() = default;

    TablesResource(
        const TablesResource& other) = default; // copy constructor
    TablesResource(TablesResource&& other) noexcept = default; // move constructor

    TablesResource& operator=(const TablesResource& other) = default; // copy assignment
    TablesResource& operator=(TablesResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, std::vector<ShallowTable>>(
        )> handler_GET_func =
            []() -> std::pair<int, std::vector<ShallowTable>>
                { throw SchemaApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, std::vector<ShallowTable>> handler_GET(
        );


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleSchemaApiException(const SchemaApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace SchemaApiResources */

using SchemaApiTableResource [[deprecated]] = SchemaApiResources::TableResource;
using SchemaApiTableTableIdResource [[deprecated]] = SchemaApiResources::TableTableIdResource;
using SchemaApiTablesResource [[deprecated]] = SchemaApiResources::TablesResource;

//
// The restbed service to actually implement the REST server
//
class  SchemaApi
{
public:
    explicit SchemaApi(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~SchemaApi();

    std::shared_ptr<SchemaApiResources::TableResource> getTableResource();
    std::shared_ptr<SchemaApiResources::TableTableIdResource> getTableTableIdResource();
    std::shared_ptr<SchemaApiResources::TablesResource> getTablesResource();

    void setResource(std::shared_ptr<SchemaApiResources::TableResource> resource);
    void setResource(std::shared_ptr<SchemaApiResources::TableTableIdResource> resource);
    void setResource(std::shared_ptr<SchemaApiResources::TablesResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setSchemaApiTableResource(std::shared_ptr<SchemaApiResources::TableResource> spSchemaApiTableResource);
    [[deprecated("use setResource()")]]
    virtual void setSchemaApiTableTableIdResource(std::shared_ptr<SchemaApiResources::TableTableIdResource> spSchemaApiTableTableIdResource);
    [[deprecated("use setResource()")]]
    virtual void setSchemaApiTablesResource(std::shared_ptr<SchemaApiResources::TablesResource> spSchemaApiTablesResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<SchemaApiResources::TableResource> m_spTableResource;
    std::shared_ptr<SchemaApiResources::TableTableIdResource> m_spTableTableIdResource;
    std::shared_ptr<SchemaApiResources::TablesResource> m_spTablesResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* SchemaApi_H_ */

