/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Column.h
 *
 * Description of single column in table
 */

#ifndef Column_H_
#define Column_H_



#include <string>
#include "LogicalColumnType.h"
#include <memory>
#include <vector>
#include <array>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of single column in table
/// </summary>
class  Column 
{
public:
    Column() = default;
    explicit Column(boost::property_tree::ptree const& pt);
    virtual ~Column() = default;

    Column(const Column& other) = default; // copy constructor
    Column(Column&& other) noexcept = default; // move constructor

    Column& operator=(const Column& other) = default; // copy assignment
    Column& operator=(Column&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// Column members

    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string value);

    /// <summary>
    /// 
    /// </summary>
    LogicalColumnType getType() const;
    void setType(LogicalColumnType value);

protected:
    std::string m_Name = "";
    LogicalColumnType m_Type = LogicalColumnType{};
};

std::vector<Column> createColumnVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<Column>(const Column& val) {
    return val.toPropertyTree();
}

template<>
inline Column fromPt<Column>(const boost::property_tree::ptree& pt) {
    Column ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* Column_H_ */
