/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CopyQuery.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

CopyQuery::CopyQuery(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string CopyQuery::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void CopyQuery::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree CopyQuery::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	pt.put("sourceFilepath", m_SourceFilepath);
	pt.put("destinationTableName", m_DestinationTableName);
	// generate tree for DestinationColumns
    tmp_node.clear();
	if (!m_DestinationColumns.empty()) {
        tmp_node = toPt(m_DestinationColumns);
		pt.add_child("destinationColumns", tmp_node);
		tmp_node.clear();
	}
	pt.put("doesCsvContainHeader", m_DoesCsvContainHeader);
	return pt;
}

void CopyQuery::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_SourceFilepath = pt.get("sourceFilepath", "");
	m_DestinationTableName = pt.get("destinationTableName", "");
	// push all items of DestinationColumns into member
	if (pt.get_child_optional("destinationColumns")) {
        m_DestinationColumns = fromPt<std::vector<std::string>>(pt.get_child("destinationColumns"));
	}
	m_DoesCsvContainHeader = pt.get("doesCsvContainHeader", false);
}

std::string CopyQuery::getSourceFilepath() const
{
    return m_SourceFilepath;
}

void CopyQuery::setSourceFilepath(std::string value)
{
    m_SourceFilepath = value;
}


std::string CopyQuery::getDestinationTableName() const
{
    return m_DestinationTableName;
}

void CopyQuery::setDestinationTableName(std::string value)
{
    m_DestinationTableName = value;
}


std::vector<std::string> CopyQuery::getDestinationColumns() const
{
    return m_DestinationColumns;
}

void CopyQuery::setDestinationColumns(std::vector<std::string> value)
{
    m_DestinationColumns = value;
}


bool CopyQuery::isDoesCsvContainHeader() const
{
    return m_DoesCsvContainHeader;
}

void CopyQuery::setDoesCsvContainHeader(bool value)
{
    m_DoesCsvContainHeader = value;
}



std::vector<CopyQuery> createCopyQueryVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<CopyQuery>();
    for (const auto& child: pt) {
        vec.emplace_back(CopyQuery(child.second));
    }

    return vec;
}

}
}
}
}

