/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CopyQuery.h
 *
 * Description of the COPY query from CSV file. Server will read the file and insert all data into selected table. When number of columns in source and target doesn&#39;t match, user have to use \&quot;destinationColumns\&quot; property to specify which columns data should be inserted into.
 */

#ifndef CopyQuery_H_
#define CopyQuery_H_



#include <string>
#include <vector>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of the COPY query from CSV file. Server will read the file and insert all data into selected table. When number of columns in source and target doesn&#39;t match, user have to use \&quot;destinationColumns\&quot; property to specify which columns data should be inserted into.
/// </summary>
class  CopyQuery 
{
public:
    CopyQuery() = default;
    explicit CopyQuery(boost::property_tree::ptree const& pt);
    virtual ~CopyQuery() = default;

    CopyQuery(const CopyQuery& other) = default; // copy constructor
    CopyQuery(CopyQuery&& other) noexcept = default; // move constructor

    CopyQuery& operator=(const CopyQuery& other) = default; // copy assignment
    CopyQuery& operator=(CopyQuery&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// CopyQuery members

    /// <summary>
    /// Path to source CSV file (filepath in perspective of running server! NOT client)
    /// </summary>
    std::string getSourceFilepath() const;
    void setSourceFilepath(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::string getDestinationTableName() const;
    void setDestinationTableName(std::string value);

    /// <summary>
    /// List of columns to copy data into. It creates a map from source columns to destination columns. Assumes that data in source file is in the same order as in this list.
    /// </summary>
    std::vector<std::string> getDestinationColumns() const;
    void setDestinationColumns(std::vector<std::string> value);

    /// <summary>
    /// Whether CSV file contains header row
    /// </summary>
    bool isDoesCsvContainHeader() const;
    void setDoesCsvContainHeader(bool value);

protected:
    std::string m_SourceFilepath = "";
    std::string m_DestinationTableName = "";
    std::vector<std::string> m_DestinationColumns;
    bool m_DoesCsvContainHeader = false;
};

std::vector<CopyQuery> createCopyQueryVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<CopyQuery>(const CopyQuery& val) {
    return val.toPropertyTree();
}

template<>
inline CopyQuery fromPt<CopyQuery>(const boost::property_tree::ptree& pt) {
    CopyQuery ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* CopyQuery_H_ */
