/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ExecuteQueryRequest.h
 *
 * Used to submit a new query for execution
 */

#ifndef ExecuteQueryRequest_H_
#define ExecuteQueryRequest_H_



#include "Query_queryDefiniton.h"
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Used to submit a new query for execution
/// </summary>
class  ExecuteQueryRequest 
{
public:
    ExecuteQueryRequest() = default;
    explicit ExecuteQueryRequest(boost::property_tree::ptree const& pt);
    virtual ~ExecuteQueryRequest() = default;

    ExecuteQueryRequest(const ExecuteQueryRequest& other) = default; // copy constructor
    ExecuteQueryRequest(ExecuteQueryRequest&& other) noexcept = default; // move constructor

    ExecuteQueryRequest& operator=(const ExecuteQueryRequest& other) = default; // copy assignment
    ExecuteQueryRequest& operator=(ExecuteQueryRequest&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// ExecuteQueryRequest members

    /// <summary>
    /// 
    /// </summary>
    Query_queryDefiniton getQueryDefinition() const;
    void setQueryDefinition(Query_queryDefiniton value);

protected:
    Query_queryDefiniton m_QueryDefinition;
};

std::vector<ExecuteQueryRequest> createExecuteQueryRequestVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<ExecuteQueryRequest>(const ExecuteQueryRequest& val) {
    return val.toPropertyTree();
}

template<>
inline ExecuteQueryRequest fromPt<ExecuteQueryRequest>(const boost::property_tree::ptree& pt) {
    ExecuteQueryRequest ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* ExecuteQueryRequest_H_ */
