/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "GetQueryResult_request.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

GetQueryResult_request::GetQueryResult_request(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string GetQueryResult_request::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void GetQueryResult_request::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree GetQueryResult_request::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	pt.put("rowLimit", m_RowLimit);
	return pt;
}

void GetQueryResult_request::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_RowLimit = pt.get("rowLimit", 0);
}

int32_t GetQueryResult_request::getRowLimit() const
{
    return m_RowLimit;
}

void GetQueryResult_request::setRowLimit(int32_t value)
{
    m_RowLimit = value;
}



std::vector<GetQueryResult_request> createGetQueryResult_requestVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<GetQueryResult_request>();
    for (const auto& child: pt) {
        vec.emplace_back(GetQueryResult_request(child.second));
    }

    return vec;
}

}
}
}
}

