/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetQueryResult_request.h
 *
 * 
 */

#ifndef GetQueryResult_request_H_
#define GetQueryResult_request_H_



#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  GetQueryResult_request 
{
public:
    GetQueryResult_request() = default;
    explicit GetQueryResult_request(boost::property_tree::ptree const& pt);
    virtual ~GetQueryResult_request() = default;

    GetQueryResult_request(const GetQueryResult_request& other) = default; // copy constructor
    GetQueryResult_request(GetQueryResult_request&& other) noexcept = default; // move constructor

    GetQueryResult_request& operator=(const GetQueryResult_request& other) = default; // copy assignment
    GetQueryResult_request& operator=(GetQueryResult_request&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// GetQueryResult_request members

    /// <summary>
    /// Maximum number of rows to return
    /// </summary>
    int32_t getRowLimit() const;
    void setRowLimit(int32_t value);

protected:
    int32_t m_RowLimit = 0;
};

std::vector<GetQueryResult_request> createGetQueryResult_requestVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<GetQueryResult_request>(const GetQueryResult_request& val) {
    return val.toPropertyTree();
}

template<>
inline GetQueryResult_request fromPt<GetQueryResult_request>(const boost::property_tree::ptree& pt) {
    GetQueryResult_request ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* GetQueryResult_request_H_ */
