/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LogicalColumnType.h
 *
 * Enum describing logical column types
 */

#ifndef LogicalColumnType_H_
#define LogicalColumnType_H_



#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Enum describing logical column types
/// </summary>
class  LogicalColumnType 
{
public:
    LogicalColumnType() = default;
    explicit LogicalColumnType(boost::property_tree::ptree const& pt);
    virtual ~LogicalColumnType() = default;

    LogicalColumnType(const LogicalColumnType& other) = default; // copy constructor
    LogicalColumnType(LogicalColumnType&& other) noexcept = default; // move constructor

    LogicalColumnType& operator=(const LogicalColumnType& other) = default; // copy assignment
    LogicalColumnType& operator=(LogicalColumnType&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);

    std::string toString() const;
    void fromString(const std::string& str);

    /////////////////////////////////////////////
    /// LogicalColumnType members
    std::string getEnumValue() const;
    void setEnumValue(const std::string& val);

protected:
    std::string m_LogicalColumnTypeEnumValue;
};

std::vector<LogicalColumnType> createLogicalColumnTypeVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<LogicalColumnType>(const LogicalColumnType& val) {
    return val.toPropertyTree();
}

template<>
inline LogicalColumnType fromPt<LogicalColumnType>(const boost::property_tree::ptree& pt) {
    LogicalColumnType ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* LogicalColumnType_H_ */
