/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MultipleProblemsError_problems_inner.h
 *
 * 
 */

#ifndef MultipleProblemsError_problems_inner_H_
#define MultipleProblemsError_problems_inner_H_



#include <string>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  MultipleProblemsError_problems_inner 
{
public:
    MultipleProblemsError_problems_inner() = default;
    explicit MultipleProblemsError_problems_inner(boost::property_tree::ptree const& pt);
    virtual ~MultipleProblemsError_problems_inner() = default;

    MultipleProblemsError_problems_inner(const MultipleProblemsError_problems_inner& other) = default; // copy constructor
    MultipleProblemsError_problems_inner(MultipleProblemsError_problems_inner&& other) noexcept = default; // move constructor

    MultipleProblemsError_problems_inner& operator=(const MultipleProblemsError_problems_inner& other) = default; // copy assignment
    MultipleProblemsError_problems_inner& operator=(MultipleProblemsError_problems_inner&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// MultipleProblemsError_problems_inner members

    /// <summary>
    /// Description of particular problem
    /// </summary>
    std::string getError() const;
    void setError(std::string value);

    /// <summary>
    /// Optional context for user (for e.g. which column caused problem). It can be helpful for troubleshooting.
    /// </summary>
    std::string getContext() const;
    void setContext(std::string value);

protected:
    std::string m_Error = "";
    std::string m_Context = "";
};

std::vector<MultipleProblemsError_problems_inner> createMultipleProblemsError_problems_innerVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<MultipleProblemsError_problems_inner>(const MultipleProblemsError_problems_inner& val) {
    return val.toPropertyTree();
}

template<>
inline MultipleProblemsError_problems_inner fromPt<MultipleProblemsError_problems_inner>(const boost::property_tree::ptree& pt) {
    MultipleProblemsError_problems_inner ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* MultipleProblemsError_problems_inner_H_ */
