/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MultipleProblemsError.h
 *
 * Error containing multiple problems about request processing. Useful when processing complex requests where multiple problems can occur at the same time.
 */

#ifndef MultipleProblemsError_H_
#define MultipleProblemsError_H_



#include "MultipleProblemsError_problems_inner.h"
#include <vector>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Error containing multiple problems about request processing. Useful when processing complex requests where multiple problems can occur at the same time.
/// </summary>
class  MultipleProblemsError 
{
public:
    MultipleProblemsError() = default;
    explicit MultipleProblemsError(boost::property_tree::ptree const& pt);
    virtual ~MultipleProblemsError() = default;

    MultipleProblemsError(const MultipleProblemsError& other) = default; // copy constructor
    MultipleProblemsError(MultipleProblemsError&& other) noexcept = default; // move constructor

    MultipleProblemsError& operator=(const MultipleProblemsError& other) = default; // copy assignment
    MultipleProblemsError& operator=(MultipleProblemsError&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// MultipleProblemsError members

    /// <summary>
    /// 
    /// </summary>
    std::vector<MultipleProblemsError_problems_inner> getProblems() const;
    void setProblems(std::vector<MultipleProblemsError_problems_inner> value);

protected:
    std::vector<MultipleProblemsError_problems_inner> m_Problems;
};

std::vector<MultipleProblemsError> createMultipleProblemsErrorVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<MultipleProblemsError>(const MultipleProblemsError& val) {
    return val.toPropertyTree();
}

template<>
inline MultipleProblemsError fromPt<MultipleProblemsError>(const boost::property_tree::ptree& pt) {
    MultipleProblemsError ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* MultipleProblemsError_H_ */
