/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "MultipleProblemsError_problems_inner.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

MultipleProblemsError_problems_inner::MultipleProblemsError_problems_inner(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string MultipleProblemsError_problems_inner::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void MultipleProblemsError_problems_inner::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree MultipleProblemsError_problems_inner::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	pt.put("error", m_Error);
	pt.put("context", m_Context);
	return pt;
}

void MultipleProblemsError_problems_inner::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_Error = pt.get("error", "");
	m_Context = pt.get("context", "");
}

std::string MultipleProblemsError_problems_inner::getError() const
{
    return m_Error;
}

void MultipleProblemsError_problems_inner::setError(std::string value)
{
    m_Error = value;
}


std::string MultipleProblemsError_problems_inner::getContext() const
{
    return m_Context;
}

void MultipleProblemsError_problems_inner::setContext(std::string value)
{
    m_Context = value;
}



std::vector<MultipleProblemsError_problems_inner> createMultipleProblemsError_problems_innerVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<MultipleProblemsError_problems_inner>();
    for (const auto& child: pt) {
        vec.emplace_back(MultipleProblemsError_problems_inner(child.second));
    }

    return vec;
}

}
}
}
}

