/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Query_queryDefiniton.h
 *
 * 
 */

#ifndef Query_queryDefiniton_H_
#define Query_queryDefiniton_H_



#include "CopyQuery.h"
#include "SelectQuery.h"
#include <string>
#include <vector>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "SelectQuery.h"
#include "CopyQuery.h"
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Query_queryDefiniton : public SelectQuery, public CopyQuery
{
public:
    Query_queryDefiniton() = default;
    explicit Query_queryDefiniton(boost::property_tree::ptree const& pt);
    virtual ~Query_queryDefiniton() = default;

    Query_queryDefiniton(const Query_queryDefiniton& other) = default; // copy constructor
    Query_queryDefiniton(Query_queryDefiniton&& other) noexcept = default; // move constructor

    Query_queryDefiniton& operator=(const Query_queryDefiniton& other) = default; // copy assignment
    Query_queryDefiniton& operator=(Query_queryDefiniton&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// Query_queryDefiniton members

    /// <summary>
    /// 
    /// </summary>
    std::string getTableName() const;
    void setTableName(std::string value);

    /// <summary>
    /// Path to source CSV file (filepath in perspective of running server! NOT client)
    /// </summary>
    std::string getSourceFilepath() const;
    void setSourceFilepath(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::string getDestinationTableName() const;
    void setDestinationTableName(std::string value);

    /// <summary>
    /// List of columns to copy data into. It creates a map from source columns to destination columns. Assumes that data in source file is in the same order as in this list.
    /// </summary>
    std::vector<std::string> getDestinationColumns() const;
    void setDestinationColumns(std::vector<std::string> value);

    /// <summary>
    /// Whether CSV file contains header row
    /// </summary>
    bool isDoesCsvContainHeader() const;
    void setDoesCsvContainHeader(bool value);

protected:
    std::string m_TableName = "";
    std::string m_SourceFilepath = "";
    std::string m_DestinationTableName = "";
    std::vector<std::string> m_DestinationColumns;
    bool m_DoesCsvContainHeader = false;
};

std::vector<Query_queryDefiniton> createQuery_queryDefinitonVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<Query_queryDefiniton>(const Query_queryDefiniton& val) {
    return val.toPropertyTree();
}

template<>
inline Query_queryDefiniton fromPt<Query_queryDefiniton>(const boost::property_tree::ptree& pt) {
    Query_queryDefiniton ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* Query_queryDefiniton_H_ */
