/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Query.h
 *
 * Description of a query in the system
 */

#ifndef Query_H_
#define Query_H_



#include "QueryStatus.h"
#include <string>
#include "Query_queryDefiniton.h"
#include <memory>
#include <vector>
#include <array>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of a query in the system
/// </summary>
class  Query 
{
public:
    Query() = default;
    explicit Query(boost::property_tree::ptree const& pt);
    virtual ~Query() = default;

    Query(const Query& other) = default; // copy constructor
    Query(Query&& other) noexcept = default; // move constructor

    Query& operator=(const Query& other) = default; // copy assignment
    Query& operator=(Query&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// Query members

    /// <summary>
    /// ID of selected Query (I propose UUID, but it is under your own discretion)
    /// </summary>
    std::string getQueryId() const;
    void setQueryId(std::string value);

    /// <summary>
    /// 
    /// </summary>
    QueryStatus getStatus() const;
    void setStatus(QueryStatus value);

    /// <summary>
    /// Whether result of this query is already available
    /// </summary>
    bool isIsResultAvailable() const;
    void setIsResultAvailable(bool value);

    /// <summary>
    /// 
    /// </summary>
    Query_queryDefiniton getQueryDefiniton() const;
    void setQueryDefiniton(Query_queryDefiniton value);

protected:
    std::string m_QueryId = "";
    QueryStatus m_Status = QueryStatus{};
    bool m_IsResultAvailable = false;
    Query_queryDefiniton m_QueryDefiniton;
};

std::vector<Query> createQueryVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<Query>(const Query& val) {
    return val.toPropertyTree();
}

template<>
inline Query fromPt<Query>(const boost::property_tree::ptree& pt) {
    Query ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* Query_H_ */
