/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QueryStatus.h
 *
 * Enum describing possible query statuses
 */

#ifndef QueryStatus_H_
#define QueryStatus_H_



#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Enum describing possible query statuses
/// </summary>
class  QueryStatus 
{
public:
    QueryStatus() = default;
    explicit QueryStatus(boost::property_tree::ptree const& pt);
    virtual ~QueryStatus() = default;

    QueryStatus(const QueryStatus& other) = default; // copy constructor
    QueryStatus(QueryStatus&& other) noexcept = default; // move constructor

    QueryStatus& operator=(const QueryStatus& other) = default; // copy assignment
    QueryStatus& operator=(QueryStatus&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);

    std::string toString() const;
    void fromString(const std::string& str);

    /////////////////////////////////////////////
    /// QueryStatus members
    std::string getEnumValue() const;
    void setEnumValue(const std::string& val);

protected:
    std::string m_QueryStatusEnumValue;
};

std::vector<QueryStatus> createQueryStatusVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<QueryStatus>(const QueryStatus& val) {
    return val.toPropertyTree();
}

template<>
inline QueryStatus fromPt<QueryStatus>(const boost::property_tree::ptree& pt) {
    QueryStatus ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* QueryStatus_H_ */
