/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QueryResult_inner_columns_inner.h
 *
 * 
 */

#ifndef QueryResult_inner_columns_inner_H_
#define QueryResult_inner_columns_inner_H_



#include <string>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  QueryResult_inner_columns_inner 
{
public:
    QueryResult_inner_columns_inner() = default;
    explicit QueryResult_inner_columns_inner(boost::property_tree::ptree const& pt);
    virtual ~QueryResult_inner_columns_inner() = default;

    QueryResult_inner_columns_inner(const QueryResult_inner_columns_inner& other) = default; // copy constructor
    QueryResult_inner_columns_inner(QueryResult_inner_columns_inner&& other) noexcept = default; // move constructor

    QueryResult_inner_columns_inner& operator=(const QueryResult_inner_columns_inner& other) = default; // copy assignment
    QueryResult_inner_columns_inner& operator=(QueryResult_inner_columns_inner&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// QueryResult_inner_columns_inner members

protected:
};

std::vector<QueryResult_inner_columns_inner> createQueryResult_inner_columns_innerVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<QueryResult_inner_columns_inner>(const QueryResult_inner_columns_inner& val) {
    return val.toPropertyTree();
}

template<>
inline QueryResult_inner_columns_inner fromPt<QueryResult_inner_columns_inner>(const boost::property_tree::ptree& pt) {
    QueryResult_inner_columns_inner ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* QueryResult_inner_columns_inner_H_ */
