/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Query.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <algorithm>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

Query::Query(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string Query::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void Query::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree Query::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	pt.put("queryId", m_QueryId);
	pt.put("isResultAvailable", m_IsResultAvailable);
	pt.add_child("queryDefiniton", m_QueryDefiniton.toPropertyTree());
	return pt;
}

void Query::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_QueryId = pt.get("queryId", "");
	m_IsResultAvailable = pt.get("isResultAvailable", false);
	if (pt.get_child_optional("queryDefiniton")) {
        m_QueryDefiniton = fromPt<Query_queryDefiniton>(pt.get_child("queryDefiniton"));
	}
}

std::string Query::getQueryId() const
{
    return m_QueryId;
}

void Query::setQueryId(std::string value)
{
    m_QueryId = value;
}


QueryStatus Query::getStatus() const
{
    return m_Status;
}

void Query::setStatus(QueryStatus value)
{
    m_Status = value;
}


bool Query::isIsResultAvailable() const
{
    return m_IsResultAvailable;
}

void Query::setIsResultAvailable(bool value)
{
    m_IsResultAvailable = value;
}


Query_queryDefiniton Query::getQueryDefiniton() const
{
    return m_QueryDefiniton;
}

void Query::setQueryDefiniton(Query_queryDefiniton value)
{
    m_QueryDefiniton = value;
}



std::vector<Query> createQueryVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<Query>();
    for (const auto& child: pt) {
        vec.emplace_back(Query(child.second));
    }

    return vec;
}

}
}
}
}

