/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SelectQuery.h
 *
 * Description of a select query (extension in project no 4)
 */

#ifndef SelectQuery_H_
#define SelectQuery_H_



#include <string>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of a select query (extension in project no 4)
/// </summary>
class  SelectQuery 
{
public:
    SelectQuery() = default;
    explicit SelectQuery(boost::property_tree::ptree const& pt);
    virtual ~SelectQuery() = default;

    SelectQuery(const SelectQuery& other) = default; // copy constructor
    SelectQuery(SelectQuery&& other) noexcept = default; // move constructor

    SelectQuery& operator=(const SelectQuery& other) = default; // copy assignment
    SelectQuery& operator=(SelectQuery&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// SelectQuery members

    /// <summary>
    /// 
    /// </summary>
    std::string getTableName() const;
    void setTableName(std::string value);

protected:
    std::string m_TableName = "";
};

std::vector<SelectQuery> createSelectQueryVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<SelectQuery>(const SelectQuery& val) {
    return val.toPropertyTree();
}

template<>
inline SelectQuery fromPt<SelectQuery>(const boost::property_tree::ptree& pt) {
    SelectQuery ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* SelectQuery_H_ */
