/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ShallowQuery.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <algorithm>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

ShallowQuery::ShallowQuery(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string ShallowQuery::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void ShallowQuery::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree ShallowQuery::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	pt.put("queryId", m_QueryId);
	return pt;
}

void ShallowQuery::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_QueryId = pt.get("queryId", "");
}

std::string ShallowQuery::getQueryId() const
{
    return m_QueryId;
}

void ShallowQuery::setQueryId(std::string value)
{
    m_QueryId = value;
}


QueryStatus ShallowQuery::getStatus() const
{
    return m_Status;
}

void ShallowQuery::setStatus(QueryStatus value)
{
    m_Status = value;
}



std::vector<ShallowQuery> createShallowQueryVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<ShallowQuery>();
    for (const auto& child: pt) {
        vec.emplace_back(ShallowQuery(child.second));
    }

    return vec;
}

}
}
}
}

