/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ShallowQuery.h
 *
 * Description of a shallow representation of a query
 */

#ifndef ShallowQuery_H_
#define ShallowQuery_H_



#include "QueryStatus.h"
#include <string>
#include <memory>
#include <vector>
#include <array>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of a shallow representation of a query
/// </summary>
class  ShallowQuery 
{
public:
    ShallowQuery() = default;
    explicit ShallowQuery(boost::property_tree::ptree const& pt);
    virtual ~ShallowQuery() = default;

    ShallowQuery(const ShallowQuery& other) = default; // copy constructor
    ShallowQuery(ShallowQuery&& other) noexcept = default; // move constructor

    ShallowQuery& operator=(const ShallowQuery& other) = default; // copy assignment
    ShallowQuery& operator=(ShallowQuery&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// ShallowQuery members

    /// <summary>
    /// ID of selected Query (I propose UUID, but it is under your own discretion)
    /// </summary>
    std::string getQueryId() const;
    void setQueryId(std::string value);

    /// <summary>
    /// 
    /// </summary>
    QueryStatus getStatus() const;
    void setStatus(QueryStatus value);

protected:
    std::string m_QueryId = "";
    QueryStatus m_Status = QueryStatus{};
};

std::vector<ShallowQuery> createShallowQueryVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<ShallowQuery>(const ShallowQuery& val) {
    return val.toPropertyTree();
}

template<>
inline ShallowQuery fromPt<ShallowQuery>(const boost::property_tree::ptree& pt) {
    ShallowQuery ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* ShallowQuery_H_ */
