/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ShallowTable.h
 *
 * Description of a shallow representation of a table (e.g. without detailed column information)
 */

#ifndef ShallowTable_H_
#define ShallowTable_H_



#include <string>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of a shallow representation of a table (e.g. without detailed column information)
/// </summary>
class  ShallowTable 
{
public:
    ShallowTable() = default;
    explicit ShallowTable(boost::property_tree::ptree const& pt);
    virtual ~ShallowTable() = default;

    ShallowTable(const ShallowTable& other) = default; // copy constructor
    ShallowTable(ShallowTable&& other) noexcept = default; // move constructor

    ShallowTable& operator=(const ShallowTable& other) = default; // copy assignment
    ShallowTable& operator=(ShallowTable&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// ShallowTable members

    /// <summary>
    /// ID of selected Table (I propose UUID, but it is under your own discretion)
    /// </summary>
    std::string getTableId() const;
    void setTableId(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string value);

protected:
    std::string m_TableId = "";
    std::string m_Name = "";
};

std::vector<ShallowTable> createShallowTableVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<ShallowTable>(const ShallowTable& val) {
    return val.toPropertyTree();
}

template<>
inline ShallowTable fromPt<ShallowTable>(const boost::property_tree::ptree& pt) {
    ShallowTable ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* ShallowTable_H_ */
