/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SystemInformation.h
 *
 * Basic information about the system
 */

#ifndef SystemInformation_H_
#define SystemInformation_H_



#include <string>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Basic information about the system
/// </summary>
class  SystemInformation 
{
public:
    SystemInformation() = default;
    explicit SystemInformation(boost::property_tree::ptree const& pt);
    virtual ~SystemInformation() = default;

    SystemInformation(const SystemInformation& other) = default; // copy constructor
    SystemInformation(SystemInformation&& other) noexcept = default; // move constructor

    SystemInformation& operator=(const SystemInformation& other) = default; // copy assignment
    SystemInformation& operator=(SystemInformation&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// SystemInformation members

    /// <summary>
    /// Version of the DBMS interface
    /// </summary>
    std::string getInterfaceVersion() const;
    void setInterfaceVersion(std::string value);

    /// <summary>
    /// Version of the DBMS system
    /// </summary>
    std::string getVersion() const;
    void setVersion(std::string value);

    /// <summary>
    /// Author of the DBMS system (will help me to automate testing)
    /// </summary>
    std::string getAuthor() const;
    void setAuthor(std::string value);

protected:
    std::string m_InterfaceVersion = "";
    std::string m_Version = "";
    std::string m_Author = "";
};

std::vector<SystemInformation> createSystemInformationVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<SystemInformation>(const SystemInformation& val) {
    return val.toPropertyTree();
}

template<>
inline SystemInformation fromPt<SystemInformation>(const boost::property_tree::ptree& pt) {
    SystemInformation ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* SystemInformation_H_ */
