/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TableSchema.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

TableSchema::TableSchema(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string TableSchema::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void TableSchema::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree TableSchema::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	pt.put("name", m_Name);
	// generate tree for Columns
    tmp_node.clear();
	if (!m_Columns.empty()) {
        tmp_node = toPt(m_Columns);
		pt.add_child("columns", tmp_node);
		tmp_node.clear();
	}
	return pt;
}

void TableSchema::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_Name = pt.get("name", "");
	// push all items of Columns into member
	if (pt.get_child_optional("columns")) {
        m_Columns = fromPt<std::vector<Column>>(pt.get_child("columns"));
	}
}

std::string TableSchema::getName() const
{
    return m_Name;
}

void TableSchema::setName(std::string value)
{
    m_Name = value;
}


std::vector<Column> TableSchema::getColumns() const
{
    return m_Columns;
}

void TableSchema::setColumns(std::vector<Column> value)
{
    m_Columns = value;
}



std::vector<TableSchema> createTableSchemaVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<TableSchema>();
    for (const auto& child: pt) {
        vec.emplace_back(TableSchema(child.second));
    }

    return vec;
}

}
}
}
}

