/**
 * MIMUW ISBD database system
 * This file describes interface between DBMS system and user.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TableSchema.h
 *
 * Description of the table in the database
 */

#ifndef TableSchema_H_
#define TableSchema_H_



#include <string>
#include "Column.h"
#include <vector>
#include <memory>
#include <vector>
#include <boost/property_tree/ptree.hpp>
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Description of the table in the database
/// </summary>
class  TableSchema 
{
public:
    TableSchema() = default;
    explicit TableSchema(boost::property_tree::ptree const& pt);
    virtual ~TableSchema() = default;

    TableSchema(const TableSchema& other) = default; // copy constructor
    TableSchema(TableSchema&& other) noexcept = default; // move constructor

    TableSchema& operator=(const TableSchema& other) = default; // copy assignment
    TableSchema& operator=(TableSchema&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// TableSchema members

    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<Column> getColumns() const;
    void setColumns(std::vector<Column> value);

protected:
    std::string m_Name = "";
    std::vector<Column> m_Columns;
};

std::vector<TableSchema> createTableSchemaVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<TableSchema>(const TableSchema& val) {
    return val.toPropertyTree();
}

template<>
inline TableSchema fromPt<TableSchema>(const boost::property_tree::ptree& pt) {
    TableSchema ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* TableSchema_H_ */
